### ISSUE TITLE
nil values

### ISSUE THREAD

**Issue by JanC** [erndev/EDSunriseSet#13]
Hi,
I tried using this library but I'm getting nil values for all NSDate vaues

```
EDSunriseSet *sunriseSet = [EDSunriseSet sunrisesetWithTimezone:[NSTimeZone localTimeZone] latitude:kDemoLatitude longitude:kDemoLongitude];
```

![screen shot 2014-02-07 at 11 43 40](https://f.cloud.github.com/assets/707703/2108795/bfed5652-8fe4-11e3-8bc3-2dfba02b73c4.png)

Besides, shouldn't the calculation be based on a given date of the year? 

cheers

**Comment by danhje** [comment]
I had the same issue, and spent some time figuring that out. Maybe you could mention somewhere that the calculation method needs to be called? Like in the README.markdown.
